### ISSUE TITLE
docker部署后，数据库没有自动创建

### ISSUE THREAD

**Issue by marco-qu** [myhhub/stock#100]
我的数据库也是用的mysql5.7的docker镜像，从log中看到已经连接上了，但是数据库没有自动创建。
我试过通过mysql命令创建一个新的instockdb数据库，但是启动InStock 的docker容器后，仍然没有自动创建相关的table，web上面显示的内容也是空的。
# cat stock_execute_job.log
2024-11-30 11:55:14,445 数据库链接信息：mysql+pymysql://root:xxxx@172.28.0.3:3306/instockdb?charset=utf8mb4
2024-11-30 11:55:14,916 ######## 任务执行时间: 2024-11-30 11:55:14.916232 #######
2024-11-30 11:55:14,916 执行信息：数据库不存在，将创建。

# cat stock_web.log
2024-11-30 11:55:15,186 Cannot connect to MySQL on 172.28.0.3:3306
Traceback (most recent call last):
  File "/data/InStock/instock/lib/torndb.py", line 101, in __init__
    self.reconnect()
  File "/data/InStock/instock/lib/torndb.py", line 119, in reconnect
    self._db = pymysql.connect(**self._db_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/usr/local/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/usr/local/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
                  ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'172.28.0.4' (using password: YES)")

看第二个log，看上去是连不上我在172.28.0.3上部署的mysql数据库，但是我在mysql上已经设置了可以让任何主机进行连接，也设置了正确的密码。（另外提一个小bug，就是我以前设置的密码中包含@字符时，连接数据库时，会把@后面的地址都当成了主机，程序需要修改下允许密码中有特殊字符）

**Comment by marco-qu** [comment]
等待一段时间，数据库有创建如下表：
mysql> show tables;
+-----------------------------------------+
| Tables_in_instockdb                     |
+-----------------------------------------+
| cn_etf_spot                             |
| cn_stock_blocktrade                     |
| cn_stock_bonus                          |
| cn_stock_fund_flow                      |
| cn_stock_fund_flow_concept              |
| cn_stock_fund_flow_industry             |
| cn_stock_indicators                     |
| cn_stock_indicators_buy                 |
| cn_stock_indicators_sell                |
| cn_stock_pattern                        |
| cn_stock_selection                      |
| cn_stock_spot                           |
| cn_stock_strategy_backtrace_ma250       |
| cn_stock_strategy_breakthrough_platform |
| cn_stock_strategy_enter                 |
| cn_stock_strategy_high_tight_flag       |
| cn_stock_strategy_keep_increasing       |
| cn_stock_strategy_parking_apron         |
| cn_stock_strategy_turtle_trade          |
+-----------------------------------------+
19 rows in set (0.00 sec)

但是在web网页上仍然显示不了内容

**Comment by marco-qu** [comment]
#73 根据这个解决
