### ISSUE TITLE
有关端口问题

### ISSUE THREAD

**Issue by Lambda-zhou** [myhhub/stock#101]
错误内容如下：
2024-11-30 04:22:39.018 Uncaught app exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
  File "/opt/conda/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
  File "/kaggle/working/stock/instock/web/web_service.py", line 86, in <module>
    main()
  File "/kaggle/working/stock/instock/web/web_service.py", line 77, in main
    http_server.listen(port)
  File "/opt/conda/lib/python3.10/site-packages/tornado/tcpserver.py", line 183, in listen
    sockets = bind_sockets(
  File "/opt/conda/lib/python3.10/site-packages/tornado/netutil.py", line 162, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 98] Address already in use

尝试：运行了restart_web.sh，重启后还是一样。。。

**Comment by Lambda-zhou** [comment]
已经解决
