### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by catch6** [myhhub/stock#121]
使用docker最新镜像还是无法启动，我的数据库是MySQL 8.4.2

**Comment by yangyang5214** [comment]
你可以把所有的完整命令都贴出来呀  这样别人好帮你看问题

**Comment by yangyang5214** [comment]
看着没啥问题

指定了 *--network host*  可以 把 *-e db_host* 去掉了 

启动后直接访问 http://localhost:9988/ 试试？  

有页面就是正常的


还有错 把 docker logs -f instock 日志贴下

**Comment by catch6** [comment]
不能去掉，数据库在另一台主机上，ip是192.168.2.3

**Comment by yangyang5214** [comment]
那就 试试？

```
docker run \
  -d \
  --name instock \
 -p 9988:9988 \
  -v /etc/timezone:/etc/timezone:ro \
  -v /etc/localtime:/etc/localtime:ro \
  -e db_host=192.168.2.3 \
  -e db_port=3306 \
  -e db_user=root \
  -e db_password=abc%40local \
  -e db_database=instock \
  mayanghua/instock:latest 
```

**Comment by catch6** [comment]
刚pull最新的镜像还是不行，mysql没有native password，这个已经过时了，mysql8.4已经移除了，不知道跟这个有关没
docker logs
```
2024-12-12 13:46:17,690 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2024-12-12 13:46:17,695 INFO RPC interface 'supervisor' initialized
2024-12-12 13:46:17,695 CRIT Server 'inet_http_server' running without any HTTP authentication checking
2024-12-12 13:46:17,695 INFO RPC interface 'supervisor' initialized
2024-12-12 13:46:17,696 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2024-12-12 13:46:17,696 INFO supervisord started with pid 1
2024-12-12 13:46:18,698 INFO spawned: 'run_job' with pid 7
2024-12-12 13:46:18,701 INFO spawned: 'run_web' with pid 8
2024-12-12 13:46:18,703 INFO spawned: 'run_cron' with pid 9
2024-12-12 13:46:19,610 WARN exited: run_job (exit status 0; not expected)
2024-12-12 13:46:19,610 INFO gave up: run_job entered FATAL state, too many start retries too quickly
2024-12-12 13:46:20,612 INFO success: run_web entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-12-12 13:46:20,612 INFO success: run_cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```
tail -500f stock_execute_job.log
```
2024-12-12 13:50:39,155 Cannot connect to MySQL on 192.168.2.3:3306
Traceback (most recent call last):
  File "/data/InStock/instock/lib/torndb.py", line 101, in __init__
    self.reconnect()
  File "/data/InStock/instock/lib/torndb.py", line 119, in reconnect
    self._db = pymysql.connect(**self._db_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/usr/local/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/usr/local/lib/python3.11/site-packages/pymysql/connections.py", line 979, in _request_authentication
    auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymysql/_auth.py", line 267, in caching_sha2_password_auth
    data = sha2_rsa_encrypt(conn.password, conn.salt, conn.server_public_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymysql/_auth.py", line 144, in sha2_rsa_encrypt
    raise RuntimeError(
RuntimeError: 'cryptography' package is required for sha256_password or caching_sha2_password auth methods
2024-12-12 13:50:39,157 服务已启动，web地址 : http://localhost:9988/
```

**Comment by yangyang5214** [comment]
最简单的方式就是 docker run 个新版本的 mariadb 吧

**Comment by catch6** [comment]
已放弃，数据库上还有其他东西，不想专门再维护一个数据库
