### ISSUE TITLE
部分数据网页展示不了， 数据库中相关表有数据。日志提示字符集有问题？

### ISSUE THREAD

**Issue by shtest1991** [myhhub/stock#123]
2024-12-05 14:48:39,522 Uncaught exception GET /instock/api_data?name=cn_stock_blocktrade&date=2024-12-04 (172.17.0.1)
HTTPServerRequest(protocol='http', host='localhost:9988', method='GET', uri='/instock/api_data?name=cn_stock_blocktrade&date=2024-12-04', version='HTTP/1.1', remote_ip='172.17.0.1')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/InStock/instock/web/dataTableHandler.py", line 68, in get
    data = self.db.query(sql)
           ^^^^^^^^^^^^^^^^^^
  File "/data/InStock/instock/lib/torndb.py", line 140, in query
    self._execute(cursor, query, parameters, kwparameters)
  File "/data/InStock/instock/lib/torndb.py", line 245, in _execute
    return cursor.execute(query, kwparameters or parameters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.11/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.11/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1267, "Illegal mix of collations (utf8mb3_general_ci,IMPLICIT) and (utf8mb3_uca1400_ai_ci,IMPLICIT) for operation '='")
2024-12-05 14:48:39,526 500 GET /instock/api_data?name=cn_stock_blocktrade&date=2024-12-04 (172.17.0.1) 6.81ms

**Comment by JackTam1993** [comment]
我也遇到同样的问题了

**Comment by shaweng** [comment]
ALTER TABLE `cn_stock_attention`
MODIFY `code` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

**Comment by myhhub** [comment]
已修改
