### ISSUE TITLE
有些表没有自动创建

### ISSUE THREAD

**Issue by sycln1** [myhhub/stock#127]
HTTPServerRequest(protocol='http', host='localhost:9988', method='GET', uri='/instock/api_data?name=cn_stock_indicators_sell&date=2024-12-05', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "C:\D\Code\stock\venv\Lib\site-packages\tornado\web.py", line 1788, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\D\Code\stock\instock\web\dataTableHandler.py", line 68, in get
    data = self.db.query(sql)
           ^^^^^^^^^^^^^^^^^^
  File "C:\D\Code\stock\instock\lib\torndb.py", line 140, in query
    self._execute(cursor, query, parameters, kwparameters)
  File "C:\D\Code\stock\instock\lib\torndb.py", line 245, in _execute
    return cursor.execute(query, kwparameters or parameters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\D\Code\stock\venv\Lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "C:\D\Code\stock\venv\Lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\D\Code\stock\venv\Lib\site-packages\pymysql\connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\D\Code\stock\venv\Lib\site-packages\pymysql\connections.py", line 825, in _read_query_result
    result.read()
  File "C:\D\Code\stock\venv\Lib\site-packages\pymysql\connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\D\Code\stock\venv\Lib\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "C:\D\Code\stock\venv\Lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\D\Code\stock\venv\Lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'instockdb.cn_stock_indicators_sell' doesn't exist")

**Comment by sycln1** [comment]
应该跑哪些任务或者脚本一次性把所有表创建出来吗

**Comment by Lockey-J** [comment]
一样在找这张表的创建。搜索代码找不到创建的位置

**Comment by Ariesly** [comment]
[#80 [](url)](https://github.com/myhhub/stock/issues/80#issuecomment-2421069142)

**Comment by sycln1** [comment]
好的，感谢
