### ISSUE TITLE
综合选股数据抓取报错cn_stock_selection

### ISSUE THREAD

**Issue by smarteng** [myhhub/stock#128]
采用docker 安装，综合选股数据抓取报错
python selection_data_daily_job.py
root@aa8a125db830:/data/InStock/instock/job# python selection_data_daily_job.py
ERROR:root:stockfetch.fetch_stocks_selection处理异常：Expecting value: line 1 column 1 (char 0)

**Comment by zkharryhhhh** [comment]
我遇到了相同的问题，定位到了在数据抓取部分，stock_selection.py，从api获取数据的返回值是500，想问下这个数据api的使用文档在哪呢，我没有找到，以及这个api现在仍然可用吗

**Comment by louyongjiu** [comment]
遇到了相同的问题 详细报错日志如下
2024-12-06 10:24:50 - INFO - 开始执行 save_nph_stock_selection_data(datetime.date(2024, 12, 6), False, ) at D:\User\Repository\stock\instock\lib\run_template.py:52 时间: 2024-12-06 10:24:50.026182
2024-12-06 10:24:51 - ERROR - stockfetch.fetch_stocks_selection处理异常：Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "D:\User\Kit\Python\Python311\Lib\site-packages\requests\models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\Kit\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\Kit\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\Kit\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\User\Repository\stock\instock\core\stockfetch.py", line 111, in fetch_stock_selection
    data = sst.stock_selection()
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\Repository\stock\instock\core\crawling\stock_selection.py", line 33, in stock_selection
    data_json = r.json()
                ^^^^^^^^
  File "D:\User\Kit\Python\Python311\Lib\site-packages\requests\models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by dominicx** [comment]
今天出现的。咨询个事情我12-03的数据貌似也不齐了，那么怎么补呢。/execute_daily_job.py 2024-12-03 貌似没有补齐

**Comment by myhhub** [comment]
已经修复，拉取新镜像
