### ISSUE TITLE
calculate_indicator.get_indicators处理异常

### ISSUE THREAD

**Issue by louyongjiu** [myhhub/stock#130]
2024-12-06 22:33:19 - ERROR - calculate_indicator.get_indicators处理异常：Length of values (0) does not match length of index (1)
Traceback (most recent call last):
  File "D:\User\Repository\stock\instock\core\indicator\calculate_indicator.py", line 136, in get_indicators
    data.loc[:, 'pdi'] = data['pdm'].values / data['atr'].values
    ~~~~~~~~^^^^^^^^^^
  File "D:\User\Kit\Python\Python311\Lib\site-packages\pandas\core\indexing.py", line 911, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "D:\User\Kit\Python\Python311\Lib\site-packages\pandas\core\indexing.py", line 1857, in _setitem_with_indexer
    self.obj[key] = value
    ~~~~~~~~^^^^^
  File "D:\User\Kit\Python\Python311\Lib\site-packages\pandas\core\frame.py", line 4311, in __setitem__
    self._set_item(key, value)
  File "D:\User\Kit\Python\Python311\Lib\site-packages\pandas\core\frame.py", line 4524, in _set_item
    value, refs = self._sanitize_column(value)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\Kit\Python\Python311\Lib\site-packages\pandas\core\frame.py", line 5266, in _sanitize_column
    com.require_length_match(value, self.index)
  File "D:\User\Kit\Python\Python311\Lib\site-packages\pandas\core\common.py", line 573, in require_length_match
    raise ValueError(
ValueError: Length of values (0) does not match length of index (1)

**Comment by jiejie-dev** [comment]
遇到同样的问题，请问你解决了吗
