### ISSUE TITLE
数据库访问出错

### ISSUE THREAD

**Issue by Metric640** [myhhub/stock#159]
更新最新版本后连接数据库出现错误
------正在执行作业中，请等待------
Traceback (most recent call last):
  File "C:\Users\<Username>\stock\instock\job\init_job.py", line 55, in main
    check_database()
  File "C:\Users\<Username>\stock\instock\job\init_job.py", line 47, in check_database
    with pymysql.connect(**mdb.MYSQL_CONN_DBAPI) as conn:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<Username>\Programs\Python\Python312\Lib\site-packages\pymysql\connections.py", line 361, in __init__
    self.connect()
  File "C:\Users\<Username>\Programs\Python\Python312\Lib\site-packages\pymysql\connections.py", line 669, in connect
    self._request_authentication()
  File "C:\Users\<Username>\Programs\Python\Python312\Lib\site-packages\pymysql\connections.py", line 979, in _request_authentication
    auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<Username>\Programs\Python\Python312\Lib\site-packages\pymysql\_auth.py", line 268, in caching_sha2_password_auth
    pkt = _roundtrip(conn, data)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<Username>\Programs\Python\Python312\Lib\site-packages\pymysql\_auth.py", line 121, in _roundtrip
    pkt = conn._read_packet()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<Username>\Programs\Python\Python312\Lib\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "C:\Users\<Username>\Programs\Python\Python312\Lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\<Username>\Programs\Python\Python312\Lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\<Username>\stock\instock\job\execute_daily_job.py", line 66, in <module>
    main()
  File "C:\Users\<Username>\stock\instock\job\execute_daily_job.py", line 40, in main
    bj.main()
  File "C:\Users\<Username>\stock\instock\job\init_job.py", line 59, in main
    create_new_database()
  File "C:\Users\<Username>\stock\instock\job\init_job.py", line 23, in create_new_database
    with pymysql.connect(**_MYSQL_CONN_DBAPI) as conn:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<Username>\Programs\Python\Python312\Lib\site-packages\pymysql\connections.py", line 361, in __init__
    self.connect()
  File "C:\Users\<Username>\Programs\Python\Python312\Lib\site-packages\pymysql\connections.py", line 669, in connect
    self._request_authentication()
  File "C:\Users\<Username>\Programs\Python\Python312\Lib\site-packages\pymysql\connections.py", line 979, in _request_authentication
    auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<Username>\Programs\Python\Python312\Lib\site-packages\pymysql\_auth.py", line 268, in caching_sha2_password_auth
    pkt = _roundtrip(conn, data)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<Username>\Programs\Python\Python312\Lib\site-packages\pymysql\_auth.py", line 121, in _roundtrip
    pkt = conn._read_packet()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<Username>\Programs\Python\Python312\Lib\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "C:\Users\<Username>\Programs\Python\Python312\Lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\<Username>\Programs\Python\Python312\Lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
Press any key to continue . . .

**Comment by myhhub** [comment]
换回了
