### ISSUE TITLE
页面打开都是空白的看过来

### ISSUE THREAD

**Issue by sofs2005** [myhhub/stock#337]
我今天刚装的docker版本，是今天刚更新的最新版。
装好后打开为什么页面都是空白的啊，什么数据都没有
执行
python execute_daily_job.py 2024-10-01 2024-12-15

Traceback (most recent call last):
  File "/data/InStock/instock/job/execute_daily_job.py", line 66, in <module>
    main()
  File "/data/InStock/instock/job/execute_daily_job.py", line 56, in main
    bdj.main()
  File "/data/InStock/instock/job/backtest_data_daily_job.py", line 98, in main
    prepare()
  File "/data/InStock/instock/job/backtest_data_daily_job.py", line 33, in prepare
    stocks_data = stock_hist_data().get_data()
                  ^^^^^^^^^^^^^^^^^
  File "/data/InStock/instock/lib/singleton_type.py", line 18, in __call__
    cls._instance = super(singleton_type, cls).__call__(*args, **kwargs)  # 创建cls的对象
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/InStock/instock/core/singleton_stock.py", line 36, in __init__
    date_start, is_cache = trd.get_trade_hist_interval(stocks[0][0])  # 提高运行效率，只运行一次
                                                       ~~~~~~^^^
IndexError: list index out of range

**Comment by sofs2005** [comment]
![image](https://github.com/user-attachments/assets/4df2360c-15e4-40a4-9910-60d2ce22f067)

**Comment by sofs2005** [comment]
看到日志报错了：

s 'sqlalchemy.sql.sqltypes.FLOAT'>, 'cn': '91日收益率', 'size': 100}, 'rate_92': {'type': <class 'sqlalchemy.sql.sqltypes.FLOAT'>, 'cn': '92日收益率', 'size': 100}, 'rate_93': {'type': <class 'sqlalchemy.sql.sqltypes.FLOAT'>, 'cn': '93日收益率', 'size': 100}, 'rate_94': {'type': <class 'sqlalchemy.sql.sqltypes.FLOAT'>, 'cn': '94日收益率', 'size': 100}, 'rate_95': {'type': <class 'sqlalchemy.sql.sqltypes.FLOAT'>, 'cn': '95日收益率', 'size': 100}, 'rate_96': {'type': <class 'sqlalchemy.sql.sqltypes.FLOAT'>, 'cn': '96日收益率', 'size': 100}, 'rate_97': {'type': <class 'sqlalchemy.sql.sqltypes.FLOAT'>, 'cn': '97日收益率', 'size': 100}, 'rate_98': {'type': <class 'sqlalchemy.sql.sqltypes.FLOAT'>, 'cn': '98日收益率', 'size': 100}, 'rate_99': {'type': <class 'sqlalchemy.sql.sqltypes.FLOAT'>, 'cn': '99日收益率', 'size': 100}, 'rate_100': {'type': <class 'sqlalchemy.sql.sqltypes.FLOAT'>, 'cn': '100日收益率', 'size': 100}}}策略list index out of range


2024-12-16 09:23:48,579 database.insert_other_db_from_df处理异常：cn_stock_fund_flow表(pymysql.err.DataError) (1366, "Incorrect integer value: '-' for column `instockdb`.`cn_stock_fund_flow`.`fund_amount` at row 1")
[SQL: INSERT INTO cn_stock_fund_flow (date, code, name, new_price, change_rate, fund_amount, fund_rate, fund_amount_super, fund_rate_super, fund_amount_large, fund_rate_large, fund_amount_medium, fund_rate_medium, fund_amount_small, fund_rate_small, change_rate_3, fund_amount_3, fund_rate_3, fund_amount_super_3, fund_rate_super_3, fund_amount_large_3, fund_rate_large_3, fund_amount_medium_3, fund_rate_medium_3, fund_amount_small_3, fund_rate_small_3, change_rate_5, fund_amount_5, fund_rate_5, fund_amount_super_5, fund_rate_super_5, fund_amount_large_5, fund_rate_large_5, fund_amount_medium_5, fund_rate_medium_5, fund_amount_small_5, fund_rate_small_5, change_rate_10, fund_amount_10, fund_rate_10, fund_amount_super_10, fund_rate_super_10, fund_amount_large_10, fund_rate_large_10, fund_amount_medium_10, fund_rate_medium_10, fund_amount_small_10, fund_rate_small_10) VALUES (%(date)s, %(code)s, %(name)s, %(new_price)s, %(change_rate)s, %(fund_amount)s, %(fund_rate)s, %(fund_amount_super)s, %(fund_rate_super)s, %(fund_amount_large)s, %(fund_rate_large)s, %(fund_amount_medium)s, %(fund_rate_medium)s, %(fund_amount_small)s, %(fund_rate_small)s, %(change_rate_3)s, %(fund_amount_3)s, %(fund_rate_3)s, %(fund_amount_super_3)s, %(fund_rate_super_3)s, %(fund_amount_large_3)s, %(fund_rate_large_3)s, %(fund_amount_medium_3)s, %(fund_rate_medium_3)s, %(fund_amount_small_3)s, %(fund_rate_small_3)s, %(change_rate_5)s, %(fund_amount_5)s, %(fund_rate_5)s, %(fund_amount_super_5)s, %(fund_rate_super_5)s, %(fund_amount_large_5)s, %(fund_rate_large_5)s, %(fund_amount_medium_5)s, %(fund_rate_medium_5)s, %(fund_amount_small_5)s, %(fund_rate_small_5)s, %(change_rate_10)s, %(fund_amount_10)s, %(fund_rate_10)s, %(fund_amount_super_10)s, %(fund_rate_super_10)s, %(fund_amount_large_10)s, %(fund_rate_large_10)s, %(fund_amount_medium_10)s, %(fund_rate_medium_10)s, %(fund_amount_small_10)s, %(fund_rate_small_10)s)]

**Comment by aimanshalou** [comment]
大哥 我连docker版本安装都不会，请教如何安装

**Comment by sofs2005** [comment]
> 大哥 我连docker版本安装都不会，请教如何安装

按教程命令来

不过我这搭出来也不好使啊

**Comment by sofs2005** [comment]
终于发现了是系统初始化的时候少建了一张表：
CREATE TABLE IF NOT EXISTS `cn_stock_attention` (
                                  `datetime` datetime(0) NULL DEFAULT NULL, 
                                  `code` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
                                  PRIMARY KEY (`code`) USING BTREE,
                                  INDEX `INIX_DATETIME`(`datetime`) USING BTREE
                                  ) CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;
大家手动建一下，再去同步一下数据，我再看看功能是不是正常

**Comment by oneyh** [comment]
> 终于发现了是系统初始化的时候少建了一张表： CREATE TABLE IF NOT EXISTS `cn_stock_attention` ( `datetime` datetime(0) NULL DEFAULT NULL, `code` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL, PRIMARY KEY (`code`) USING BTREE, INDEX `INIX_DATETIME`(`datetime`) USING BTREE ) CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic; 大家手动建一下，再去同步一下数据，我再看看功能是不是正常

我的本来就有这张表，但是这张表中没有任何数据。好像是，他的表时动态创建的，一开始如果用不到就不创建，用到了再创建。

**Comment by sofs2005** [comment]
> > 终于发现了是系统初始化的时候少建了一张表： CREATE TABLE IF NOT EXISTS `cn_stock_attention` ( `datetime` datetime(0) NULL DEFAULT NULL, `code` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL, PRIMARY KEY (`code`) USING BTREE, INDEX `INIX_DATETIME`(`datetime`) USING BTREE ) CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic; 大家手动建一下，再去同步一下数据，我再看看功能是不是正常
> 
> 我的本来就有这张表，但是这张表中没有任何数据。好像是，他的表时动态创建的，一开始如果用不到就不创建，用到了再创建。

不是，这是在初始化的时候就建的基础表，建库后就是这个表

**Comment by sofs2005** [comment]
今天的综合选股又空白了。。。

**Comment by q4351251** [comment]
`cn_stock_attention` (关注列表)表没创建，报错`pymysql.err.ProgrammingError: (1146, "Table 'instockdb.cn_stock_attention' doesn't exist")`, 导致个股数据的页面全都空白, 看代码初始化没有创建这个表...，按照楼主的方法手动创建该表可解决。
```
CREATE TABLE IF NOT EXISTS cn_stock_attention (
datetime datetime(0) NULL DEFAULT NULL,
code varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
PRIMARY KEY (code) USING BTREE,
INDEX INIX_DATETIME(datetime) USING BTREE
) CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;
```
还是希望作者修复一下 😀

**Comment by wangsuozhu1** [comment]
综合选股一直空白，前两个星期还正常，这两个星期一直打不开，查了数据库综合选股有这张表，且数据也有，但前端就是加载不出来不知道啥原因啊

**Comment by wangsuozhu1** [comment]
pymysql.err.ProgrammingError: (1146, "Table 'instockdb.cn_stock_strategy_low_backtrace_increase' doesn't exist")
谁有这个sql 语句，只能看到这个报错

**Comment by wangsuozhu1** [comment]
> 今天的综合选股又空白了。。。

我也是，空白了好久了，找不到原因。。

**Comment by sofs2005** [comment]
看日志cn_stock_strategy_low_atr这个表没有，也没找到定义，知道的说一下

**Comment by twfxr** [comment]
> 终于发现了是系统初始化的时候少建了一张表： CREATE TABLE IF NOT EXISTS `cn_stock_attention` (创建表格 if not exists `cn_stock_attention` ( `datetime` datetime(0) NULL DEFAULT NULL, `datetime` datetime(0) NULL DEFAULT NULL、 `code` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL, `code` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL、 PRIMARY KEY (`code`) USING BTREE,主键 ( `code` ) 使用 btree、 INDEX `INIX_DATETIME`(`datetime`) USING BTREE使用 btree 索引 `INIX_DATETIME` ( `datetime` ) ) CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;)CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic； 大家手动建一下，再去同步一下数据，我再看看功能是不是正常

怎样手动建这个表？

**Comment by avengewolf** [comment]
用DOCKER搭建后，没有数据，只有空白

**Comment by avengewolf** [comment]
2024-12-28 12:43:31,061 stockfetch.fetch_stock_top_data处理异常：HTTPSConnectionPool(host='vip.stock.finance.sina.com.cn', port=443): Max retries exceeded with url: /q/go.php/vLHBData/kind/ggtj/index.phtml?last=5&p=1 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f095386ac90>: Failed to resolve 'vip.stock.finance.sina.com.cn' ([Errno -3] Temporary failure in name resolution)"))
这是什么意思
另外stock_web.log
root@instock:/data# cat InStock/instock/log/stock_web.log
2024-12-28 12:41:51,011 服务已启动，web地址 : http://localhost:9988/
2024-12-28 12:42:30,713 stockfetch.fetch_stocks_trade_date处理异常：HTTPSConnectionPool(host='finance.sina.com.cn', port=443): Max retries exceeded with url: /realstock/company/klc_td_sh.txt (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f2bceee8410>: Failed to resolve 'finance.sina.com.cn' ([Errno -3] Temporary failure in name resolution)"))
2024-12-28 12:42:44,004 Uncaught exception GET /instock/api_data?name=cn_stock_spot&date=2024-12-28 (172.17.0.1)
HTTPServerRequest(protocol='http', host='192.168.1.8:9988', method='GET', uri='/instock/api_data?name=cn_stock_spot&date=2024-12-28', version='HTTP/1.1', remote_ip='172.17.0.1')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/InStock/instock/web/dataTableHandler.py", line 69, in get
    data = self.db.query(sql,date)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/InStock/instock/lib/torndb.py", line 140, in query
    self._execute(cursor, query, parameters, kwparameters)
  File "/data/InStock/instock/lib/torndb.py", line 245, in _execute
    return cursor.execute(query, kwparameters or parameters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.11/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.11/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'instockdb.cn_stock_spot' doesn't exist")
2024-12-28 12:42:44,010 500 GET /instock/api_data?name=cn_stock_spot&date=2024-12-28 (172.17.0.1) 7.21ms
