### ISSUE TITLE
具体个股页面无法显示 

### ISSUE THREAD

**Issue by AleDaDa** [myhhub/stock#49]
`[bokeh]` setting log level to: 'error'
bokeh-3.2.2.min.js:179  Uncaught (in promise) Error: unknown property WheelZoomTool.renderers
    at d.property (bokeh-3.2.2.min.js:179:2416)
    at d.initialize_props (bokeh-3.2.2.min.js:179:4518)
    at p._decode_object_ref (bokeh-3.2.2.min.js:211:4877)
    at p._decode (bokeh-3.2.2.min.js:211:1779)
    at bokeh-3.2.2.min.js:211:2249
    at f (bokeh-3.2.2.min.js:178:450)
    at p._decode_plain_array (bokeh-3.2.2.min.js:211:2237)
    at p._decode (bokeh-3.2.2.min.js:211:928)
    at p._decode_plain_object (bokeh-3.2.2.min.js:211:2340)
    at p._decode (bokeh-3.2.2.min.js:211:1066)
`
环境 ： win10, python 3.12
requirements.txt 的内容全改为了 >=

**Comment by lewyu** [comment]
+1，同问

**Comment by wildwalkbro** [comment]
pip uninstall bokeh
pip install bokeh==3.2.2
