### ISSUE TITLE
docker安装后，有行业数据，没有任何个股数据

### ISSUE THREAD

**Issue by lazebird** [myhhub/stock#73]
是缺什么东西吗？

root@d22270580f68:/data# cat InStock/instock/log/stock_execute_job.log
2024-09-30 17:15:47,350 数据库链接信息：mysql+pymysql://root:root@InStockDbService:3306/instockdb?charset=utf8mb4
2024-09-30 17:15:48,182 ######## 任务执行时间: 2024-09-30 17:15:48.182954 #######
2024-09-30 17:15:48,184 执行信息：数据库不存在，将创建。
2024-09-30 17:25:34,535 ######## 完成任务, 使用时间: 586.3529043197632 秒 #######
root@d22270580f68:/data#

**Comment by lazebird** [comment]
root@c3ad9f9d63b6:/data# cat InStock/instock/log/stock_web.log

2024-10-08 13:25:14,982 Error connecting to MySQL on InStockDbService:3306
2024-10-08 13:25:14,983 Uncaught exception GET /instock/api_data?name=cn_stock_selection&date=2024-09-30 (172.17.0.1)
HTTPServerRequest(protocol='http', host='localhost:9988', method='GET', uri='/instock/api_data?name=cn_stock_selection&date=2024-09-30', version='HTTP/1.1', remote_ip='172.17.0.1')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/InStock/instock/web/dataTableHandler.py", line 68, in get
    data = self.db.query(sql)
           ^^^^^^^^^^^^^^^^^^
  File "/data/InStock/instock/lib/torndb.py", line 140, in query
    self._execute(cursor, query, parameters, kwparameters)
  File "/data/InStock/instock/lib/torndb.py", line 245, in _execute
    return cursor.execute(query, kwparameters or parameters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.11/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.11/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1267, "Illegal mix of collations (utf8mb3_general_ci,IMPLICIT) and (utf8mb3_uca1400_ai_ci,IMPLICIT) for operation '='")
2024-10-08 13:25:14,992 500 GET /instock/api_data?name=cn_stock_selection&date=2024-09-30 (172.17.0.1) 10.99ms

**Comment by myhhub** [comment]
报错："Error connecting to MySQL  on XXX" 通常表明Python程序在尝试连接到MySQL数据库时遇到了问题。
这个错误可能有多种原因，包括但不限于：
1.客户端缺 MySQLClient 包。
2.MySQL 服务未运行。
3.网络问题导致无法到达 MySQL 服务器。
4.连接信息错误，例如主机名、端口号、用户名或密码不正确。
5.数据库服务器的防火墙设置阻止了连接。
6.MySQL 用户权限不足或未授权远程连接。

**Comment by lazebird** [comment]
能具体说下吗，我mariadb也是用docker,完全按照docker方式安装的，docker运行也是正常没有报错；然后页面上行业数据是有的，所以不是很明白具体是什么错误，有办法具体定位下吗
另外错误会不会是格式问题： pymysql.err.OperationalError: (1267, "Illegal mix of collations (utf8mb3_general_ci,IMPLICIT) and (utf8mb3_uca1400_ai_ci,IMPLICIT) for operation '='")


> 报错："Error connecting to MySQL on XXX" 通常表明Python程序在尝试连接到MySQL数据库时遇到了问题。 这个错误可能有多种原因，包括但不限于： 1.客户端缺 MySQLClient 包。 2.MySQL 服务未运行。 3.网络问题导致无法到达 MySQL 服务器。 4.连接信息错误，例如主机名、端口号、用户名或密码不正确。 5.数据库服务器的防火墙设置阻止了连接。 6.MySQL 用户权限不足或未授权远程连接。

**Comment by zhangxyiang** [comment]
好像不太行；我的排序规则都是对的。
![image](https://github.com/user-attachments/assets/cd79e56e-4e1a-4900-a87d-08fc4051e221)

**Comment by zhangxyiang** [comment]
好像不太行；我的排序规则都是对的。
![image](https://github.com/user-attachments/assets/cd79e56e-4e1a-4900-a87d-08fc4051e221)

**Comment by AltenLi** [comment]
```sql
ALTER TABLE `cn_etf_spot` COLLATE 'utf8mb3_general_ci';
ALTER TABLE cn_stock_attention COLLATE='utf8mb3_general_ci';
ALTER TABLE cn_stock_blocktrade COLLATE='utf8mb3_general_ci';
ALTER TABLE cn_stock_bonus COLLATE='utf8mb3_general_ci';
ALTER TABLE cn_stock_fund_flow COLLATE='utf8mb3_general_ci';
ALTER TABLE cn_stock_fund_flow_concept COLLATE='utf8mb3_general_ci';
ALTER TABLE cn_stock_fund_flow_industry COLLATE='utf8mb3_general_ci';
ALTER TABLE cn_stock_indicators COLLATE='utf8mb3_general_ci';
ALTER TABLE cn_stock_indicators_buy COLLATE='utf8mb3_general_ci';
ALTER TABLE cn_stock_pattern COLLATE='utf8mb3_general_ci';
ALTER TABLE cn_stock_selection COLLATE='utf8mb3_general_ci';
ALTER TABLE cn_stock_spot COLLATE='utf8mb3_general_ci';
ALTER TABLE cn_stock_spot_buy COLLATE='utf8mb3_general_ci';
ALTER TABLE cn_stock_strategy_backtrace_ma250 COLLATE='utf8mb3_general_ci';
ALTER TABLE cn_stock_strategy_breakthrough_platform COLLATE='utf8mb3_general_ci';
ALTER TABLE cn_stock_strategy_climax_limitdown COLLATE='utf8mb3_general_ci';
ALTER TABLE cn_stock_strategy_enter COLLATE='utf8mb3_general_ci';
ALTER TABLE cn_stock_strategy_high_tight_flag COLLATE='utf8mb3_general_ci';
ALTER TABLE cn_stock_strategy_keep_increasing COLLATE='utf8mb3_general_ci';
ALTER TABLE cn_stock_strategy_parking_apron COLLATE='utf8mb3_general_ci';
ALTER TABLE cn_stock_strategy_turtle_trade COLLATE='utf8mb3_general_ci';
ALTER TABLE cn_stock_top COLLATE='utf8mb3_general_ci';
```

**Comment by myhhub** [comment]
获取最新，已强制utf8mb4，不会再出现字符的问题。
