### ISSUE TITLE
没股票数据

### ISSUE THREAD

**Issue by liuwaei** [myhhub/stock#75]
我看了根据没这张表stock.cn_stock_attention 这个表咋来的

HTTPServerRequest(protocol='http', host='localhost:9988', method='GET', uri='/instock/api_data?name=cn_stock_spot&date=2024-10-08', version='HTTP/1.1', remote_ip='14.19.204.221')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/stock/instock/web/dataTableHandler.py", line 68, in get
    data = self.db.query(sql)
           ^^^^^^^^^^^^^^^^^^
  File "/root/stock/instock/lib/torndb.py", line 140, in query
    self._execute(cursor, query, parameters, kwparameters)
  File "/root/stock/instock/lib/torndb.py", line 245, in _execute
    return cursor.execute(query, kwparameters or parameters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.11/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.11/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'stock.cn_stock_attention' doesn't exist")
2024-10-08 22:46:37,005 500 GET /instock/api_data?name=cn_stock_spot&date=2024-10-08 (14.19.204.221) 8.63ms

**Comment by myhhub** [comment]
用的是旧版本，为了系统效率cn_stock_attention在创建数据库时一同创建。
可以通过如下方法解决：
1.手动创建，执行创建sql语句。在代码中查找：CREATE TABLE IF NOT EXISTS `cn_stock_attention` 即可得到sql语句。
2.删除数据库。
