### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Shaw-shaw** [myhhub/stock#89]
ypeError: 'NoneType' object is not subscriptable
root@ffea30034de5:/data/InStock/instock/job# python3 execute_daily_job.py 2024-11-13
Traceback (most recent call last):
  File "/data/InStock/instock/job/execute_daily_job.py", line 66, in <module>
    main()
  File "/data/InStock/instock/job/execute_daily_job.py", line 56, in main
    bdj.main()
  File "/data/InStock/instock/job/backtest_data_daily_job.py", line 98, in main
    prepare()
  File "/data/InStock/instock/job/backtest_data_daily_job.py", line 33, in prepare
    stocks_data = stock_hist_data().get_data()
                  ^^^^^^^^^^^^^^^^^
  File "/data/InStock/instock/lib/singleton_type.py", line 18, in __call__
    cls._instance = super(singleton_type, cls).__call__(*args, **kwargs)  # 创建cls的对象
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/InStock/instock/core/singleton_stock.py", line 31, in __init__
    _subset = stock_data(date).get_data()[list(tbs.TABLE_CN_STOCK_FOREIGN_KEY['columns'])]
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by jetamie** [comment]
我也有这个问题
